config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :items
  get 'home/get'

  get 'home/past'

  root 'home#get'
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  # http://stackoverflow.com/questions/15040964/warning-cant-verify-csrf-token-authenticity-in-case-of-api-development
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to "/activities ", notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to "/activities", notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:excercise, :calories_burned, :duration, :date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def get
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  # http://stackoverflow.com/questions/15040964/warning-cant-verify-csrf-token-authenticity-in-case-of-api-development
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to "/items", notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
        # render to the index_path instead of the show
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to "/items", notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully deleted.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:itemName, :calories, :totalFat, :sodium, :totalCarb, :protein)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/activities/_form.html.erb
<br><br><br>
<%= form_for(activity) do |f| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="formTable">
<table>
  <tr>
    <td>
      <%= f.label :excercise %>
      <%= f.text_field :excercise %>
    </td>
    <td>
      <%= f.label :calories_burned %>
      <%= f.text_field :calories_burned %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label :duration %>
      <%= f.time_select :duration %>
    </td>
    <td>
      <%= f.label :date %>
      <%= f.date_select :date %>
    </td>
  </tr>
</table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/activities/edit.html.erb
<br><br>

<div class="link">
  <%= link_to"Back to the Excercise Table", activities_path %>
</div>

<div class="formHeading">
  <h1>Edit Activity</h1>
</div>


<%= render 'form', activity: @activity %>

app/views/activities/index.html.erb
<br><br>
<p id="notice"><%= notice %></p>

<div class="subHeading">

  <div>
    <h2>Activity Tracker</h2>
    <% date = Time.new %>
    <h1><%= date.month.to_s + "/" + date.day.to_s + "/" + date.year.to_s %></h1>
  </div>
  <%= link_to"+ Add Excercies", new_activity_path  %>
</div>


<div class="tableDiv">
<table>
  <thead>
    <tr>
      <th>Excercise</th>
      <th>Calories burned</th>
      <th>Duration</th>
      <th>Date</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.excercise %></td>
        <td><%= activity.calories_burned %></td>
        <td><%= activity.duration.hour %> hours <%= activity.duration.min %> minutes</td>
        <td><%= activity.date %></td>

        <td><%= link_to 'Edit', edit_activity_path(activity) %>
        <%= link_to 'Destroy', activity, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

</div>

app/views/activities/new.html.erb
<br><br><br><br>

<div class="link">
  <%= link_to 'Back to the Activity Table', activities_path %>
</div>

<div class="formHeading">
  <h1>Add Activity</h1>
</div>


<%= render 'form', activity: @activity %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Excercise:</strong>
  <%= @activity.excercise %>
</p>

<p>
  <strong>Calories burned:</strong>
  <%= @activity.calories_burned %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @activity.duration %>
</p>

<p>
  <strong>Date:</strong>
  <%= @activity.date %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/home/get.html.erb
<!-- <h1>Home#get</h1>
<p>Find me in app/views/home/get.html.erb</p> -->

<br><br><br><br><br><br><br><br>

<div class="heading">
  <h1>Welcome,</h1>
<br>
  <center><div>
    <center><h4>Daily Tracker is a web application <br>
                used to help manage people's <br>
                nutritional intake for each day.</h4></center>
  </div></center>
  <br>
  <center><h4><%= link_to"Click here to view food log", :controller=>"items", :action=>"index" %></h4></center>
  <br><br>
  <center><h4><%= link_to"Click here to view excercise log", :controller=>"activities", :action=>"index" %></h4></center>

  <br><br>
  <center><%= image_tag("runner.png", :class=>"runningImage") %></center>

</div>

app/views/items/_form.html.erb
<br><br><br>

<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="formTable">
    <table>
      <tr>
        <td>
          <%= f.label :item_Name %>
          <%= f.text_field :itemName %>
        </td>
        <td>
          <%= f.label :calories %>
          <%= f.text_field :calories %>
        </td>
        <td>
          <%= f.label :total_Fat %>
          <%= f.text_field :totalFat %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label :sodium %>
          <%= f.text_field :sodium %>
        </td>
        <td>
          <%= f.label :total_Carb %>
          <%= f.text_field :totalCarb %>
        </td>
        <td>
          <%= f.label :protein %>
          <%= f.text_field :protein %>
        </td>
      </tr>
    </table>
    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>
</div>

app/views/items/edit.html.erb
<br><br>

<div class="link">
  <%= link_to"Back to the Nutrition Table", items_path %>
</div>

<div class="formHeading">
  <h1>Edit Item</h1>
</div>

<%= render 'form', item: @item %>

app/views/items/index.html.erb
<br><br>
<p id="notice"><%= notice %></p>

<div class="subHeading">
    <div>
      <h2>Nutrition Tracker</h4>
      <% date = Time.new %>
      <h1><%= date.month.to_s + "/" + date.day.to_s + "/" + date.year.to_s %></h1>
    </div>
  <%= link_to"+ Add Item", new_item_path  %>
</div>


<div class="tableDiv">
  <table>
    <thead>
      <tr>
        <th>Item</th>
        <th>Calories (cal.)</th>
        <th>Total Fat (g.)</th>
        <th>Sodium (mg.)</th>
        <th>Total Carb (g.)</th>
        <th>Protein (g.)</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.itemName %></td>
          <td><%= item.calories %></td>
          <td><%= item.totalFat %></td>
          <td><%= item.sodium %></td>
          <td><%= item.totalCarb %></td>
          <td><%= item.protein %></td>
          <td>
              <%= link_to 'Edit', edit_item_path(item) %>
              <%= link_to 'Destroy', item, method: :delete%>
              <%= %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br><br>
  <table class="second">
    <thead>
      <th><strong><h3>Total:</h3></strong></th>
      <% sum = 0 %>
      <th><%= x = @items.sum('calories')%><% sum += x %></th>
      <th><%= x = @items.sum('totalFat') %><% sum += x %></th>
      <th><%= x = @items.sum('sodium') %><% sum += x %></th>
      <th><%= x = @items.sum('totalCarb') %><% sum += x %></th>
      <th><%= x = @items.sum('protein') %><% sum += x %></th>
      <th colspan="3">
        <%if sum < 3000 %>
          <%= "Great" %>
        <% elsif sum < 4000 %>
          <%= "Almost There" %>
        <% else %>
          <%= "Try Better" %>
        <% end %>
      </th>
    </thead>
  </table>

</div>

app/views/items/new.html.erb
<!-- Eliminate this view -->
<br><br><br><br>

<div class="link">
  <%= link_to"Back to the Nutrition Table", items_path %>
</div>

<div class="formHeading">
  <h1>Add Item</h1>
</div>


<%= render 'form', item: @item %>

app/views/items/show.html.erb
<br><br><br>
<br><br><br>

<!--
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %> -->


<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>


<!-- Want to delete this file -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= favicon_link_tag 'DT-logo.jpg' %>
<html>
  <head>
    <title>DailyTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="body">


        <div class="navbar">
          <div>
            <%= link_to image_tag("DT-logo.jpg"), "/", :class => "logo"%>
          </div>

          <div id="title">
            <h1>Daily Tracker</h1>
          </div>

          <div>
            <ul>
              <li><%= link_to"Excercise", :controller=>"activities", :action=>"index" %></li>
              <li><%= link_to"Nutrition", :controller=>"items", :action=>"index" %></li>
            </ul>
          </div>

        </div>
<br><br><br><br>

    <%= yield %>

    <footer>
      <p>Created by Mitchell Klich, Rey-Nathan Gray, Robert Ramirez</p>
    </footer>



  </body>
</html>